secret_key_base: secret_key_base
stripe:
  publishable_key: pk_12345
  secret_key: sk_12345
omniauth:
  google:
    client_id: client_id
    client_secret: client_secret
  facebook:
    app_id: app_id
    app_secret: app_secret