# <% require_relative 'config/deploy/terraform_variables' %>

image: rails-template/web-server

service: rails-template

servers:
  web: 
    - 3.140.162.112

proxy:
  app_port: 80
  healthcheck:
    path: /up
    interval: 5
    timeout: 5

registry:
  server: 184967710807.dkr.ecr.us-east-2.amazonaws.com
  username: AWS
  password: <%= %x(aws ecr get-login-password --region us-east-2) %>
env:
  secret:
    - RAILS_MASTER_KEY
    - RDS_PASSWORD
    - RDS_HOST
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

ssh:
  user: ubuntu

asset_path: /rails/public/assets

builder:
  arch: amd64
  args:
    RUBY_VERSION: "3.2.2"
  secrets:
    - RAILS_MASTER_KEY