# <% require_relative 'config/deploy/terraform_variables' %>

image: <app-name>/web-server

service: <app-name>

servers:
  web: <% web_server_ips.each do |web_server_ip| %>
    - <%= web_server_ip %>
    <% end %>

proxy:
  app_port: 80
  healthcheck:
    path: /up
    interval: 5
    timeout: 5

registry:
  server: <%= ecr %>
  username: AWS
  password: <%= %x(aws ecr --profile <your-profile-name> get-login-password) %>

env:
  secret:
    - RAILS_MASTER_KEY
    - RDS_PASSWORD
    - RDS_HOST
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

ssh:
  proxy: ubuntu@<%= bastion_ip %>
  user: ubuntu

asset_path: /rails/public/assets

builder:
  arch: amd64
  args:
    RUBY_VERSION: "3.2.2"
  secrets:
    - RAILS_MASTER_KEY
