image: rails-template/web-server

service: rails_template

servers:
  web:
    - &web_server <web server ip>

proxy:
  app_port: 80
  healthcheck:
    path: /up
    interval: 5
    timeout: 5

registry:
  server: 111111111111.dkr.ecr.us-east-1.amazonaws.com # Replace with your ECR registry
  username: AWS
  password: <%= %x(aws ecr --profile ew get-login-password) %>

env:
  secret:
    - RAILS_MASTER_KEY
    - RDS_PASSWORD
    - RDS_HOST
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

ssh:
  proxy: ubuntu@<bastion public ip>
  user: ubuntu

asset_path: /rails/public/assets

builder:
  arch: amd64
  args:
    RUBY_VERSION: "3.2.2"
  secrets:
    - RAILS_MASTER_KEY
